###USERS
### Read All Users
GET http://localhost:4000/user-api/users

### Read user by Id
GET http://localhost:4000/user-api/users/698dd8554ce14db3e88993de

### Create User
POST  http://localhost:4000/user-api/users
Content-Type: application/json

{
    "username":"Dinesh",
    "password":"dinesh@123",
    "age":20
}

###Update user by id
PUT  http://localhost:4000/user-api/users/698dd8554ce14db3e88993de
Content-Type: application/json

{
    "username":"shiva",
    "password":"shiva@123",
    "age":21
}

### Delete user by id

DELETE  http://localhost:4000/user-api/users/698dd8554ce14db3e88993de



###----PRODUCTS
### Read all Products
GET http://localhost:4000/product-api/products

### Create Product

POST http://localhost:4000/product-api/products
Content-Type: application/json

{
    "productname":"chessboard",
    "price":500
}

### Get Product by id
GET http://localhost:4000/product-api/products/698dd8e94ce14db3e88993e5


### Update user by id
PUT http://localhost:4000/product-api/products/698dd8e94ce14db3e88993e5
Content-Type: application/json

{
    "productname":"Laptop",
    "price":60000
}