###   ...Users

###GET USER
GET http://localhost:3000/user-api/users

### ADD USER

POST http://localhost:3000/user-api/users
Content-Type: application/json

{
    "id":1,
    "name":"karthik",
    "age":20
}

### GET USER BY ID

GET http://localhost:3000/user-api/users/1

###Updating user by id
PUT http://localhost:3000/user-api/users/1
Content-Type: application/json

{
    "name": "Dinesh Karthik",
    "age": 35
}


###Deleting user 

DELETE http://localhost:3000/user-api/users/1


###   ...Products

### Getting all products
GET http://localhost:3000/products-api/products


### Adding a new products
POST http://localhost:3000/products-api/products
Content-Type: application/json

{
    "productId": 2,
    "name":"Redmi Note 10",
    "price":5000,
    "brand":"MI"
}

### Get product by id
GET http://localhost:3000/products-api/products/2

### Update product by id
PUT http://localhost:3000/products-api/products/2
Content-Type: application/json

{
    "price": 6000,
    "name": "Redmi Note 10 Pro"
}


### Delete product

DELETE http://localhost:3000/products-api/products/2
